// ignore_for_file: public_member_api_docs

import 'package:flutter/material.dart' hide Colors;
import 'package:flutter/scheduler.dart';

import 'colors/colors.dart';
import 'src/colors.dart';
import 'src/dimens.dart';
import 'text_styles.dart';

/// A class that provides access to theme-related details from anywhere in the
/// app. Through an instance of the [ThemeProvider] class, it is possible to
/// access font family, various app colors, update app theme, and get text style
class ThemeProvider {
  factory ThemeProvider() => _instance;

  ThemeProvider._internal();

  static final ThemeProvider _instance = ThemeProvider._internal();

  final Map<TextStyle, Map<Color, TextStyle>> _textStyle =
      <TextStyle, Map<Color, TextStyle>>{};

  /*
  In case of a theme change, use IDE refactoring technique to rename the values
  So they can be reflected wherever they are used in the app with ease.
  */
  static const double margin02 = Dimens.margin02;

  static const double margin04 = Dimens.margin04;

  static const double margin08 = Dimens.margin08;

  static const double margin12 = Dimens.margin12;

  static const double margin16 = Dimens.margin16;

  static const double margin24 = Dimens.margin24;

  static const double margin32 = Dimens.margin32;

  static const double margin48 = Dimens.margin48;

  static const double margin72 = Dimens.margin72;

  static const double margin96 = Dimens.margin96;

  static const double borderRadius04 = Dimens.borderRadius04;

  static const double borderRadius08 = Dimens.borderRadius08;

  static const double borderRadius16 = Dimens.borderRadius16;

  static const double iconSize16 = Dimens.iconSize16;

  static const double iconSize24 = Dimens.iconSize24;

  static const double iconSize32 = Dimens.iconSize32;

  bool _isDarkTheme =
      SchedulerBinding.instance.window.platformBrightness == Brightness.dark;

  bool get isDarkTheme => _isDarkTheme;

  String get fontFamily => TextStyles.appFontFamily;

  // Colors getters
  @Deprecated('Use `colors.coral` instead')
  Color get brandCoralColor => BrandColors.coral;

  @Deprecated('Use `colors.blue` instead')
  Color get brandGreenishColor => BrandColors.greenish;

  @Deprecated('Use `colors.orange` instead')
  Color get brandOrangeColor => BrandColors.orange;

  @Deprecated('Use `colors.danger` instead')
  Color get accentRedColor =>
      _isDarkTheme ? DarkThemeColors.accentRed : LightThemeColors.accentRed;

  @Deprecated('Use `colors.success` instead')
  Color get accentGreenColor =>
      _isDarkTheme ? DarkThemeColors.accentGreen : LightThemeColors.accentGreen;

  @Deprecated('Use `colors.warning` instead')
  Color get accentYellowColor => _isDarkTheme
      ? DarkThemeColors.accentYellow
      : LightThemeColors.accentYellow;

  @Deprecated('Use `colors.prominent` instead')
  Color get base01Color =>
      _isDarkTheme ? DarkThemeColors.base01 : LightThemeColors.base01;

  @Deprecated('Use `colors.general` instead')
  Color get base02Color =>
      _isDarkTheme ? DarkThemeColors.base02 : LightThemeColors.base02;

  @Deprecated('Use `colors.lessProminent` instead')
  Color get base03Color =>
      _isDarkTheme ? DarkThemeColors.base03 : LightThemeColors.base03;

  @Deprecated('Use `colors.disabled` instead')
  Color get base04Color =>
      _isDarkTheme ? DarkThemeColors.base04 : LightThemeColors.base04;

  @Deprecated('Use `colors.active` instead')
  Color get base05Color =>
      _isDarkTheme ? DarkThemeColors.base05 : LightThemeColors.base05;

  @Deprecated('Use `colors.hover` instead')
  Color get base06Color =>
      _isDarkTheme ? DarkThemeColors.base06 : LightThemeColors.base06;

  @Deprecated('Use `colors.secondary` instead')
  Color get base07Color =>
      _isDarkTheme ? DarkThemeColors.base07 : LightThemeColors.base07;

  @Deprecated('Use `colors.primary` instead')
  Color get base08Color =>
      _isDarkTheme ? DarkThemeColors.base08 : LightThemeColors.base08;

  @Deprecated('Use `colors.green` instead')
  Color get greenColor =>
      _isDarkTheme ? DarkThemeColors.green : LightThemeColors.green;

  @Deprecated('Use `colors.information` instead')
  Color get informationColor =>
      _isDarkTheme ? DarkThemeColors.information : LightThemeColors.information;

  @Deprecated('Use `colors.disabled` instead')
  Color get disabledColor =>
      _isDarkTheme ? DarkThemeColors.disabled : LightThemeColors.disabled;

  Colors get colors => Colors(isDark: _isDarkTheme);

  @visibleForTesting
  TextStyle getStyle({
    required TextStyle textStyle,
    required Color color,
  }) {
    ArgumentError.checkNotNull(textStyle, 'textStyle');
    ArgumentError.checkNotNull(color, 'color');
    _textStyle.putIfAbsent(textStyle, () => <Color, TextStyle>{});
    _textStyle[textStyle]
        ?.putIfAbsent(color, () => textStyle.copyWith(color: color));

    return _textStyle[textStyle]![color]!;
  }

  /// The style of text is generated by calling this function,
  ///
  /// The `type` argument must not be null, and if null is passed, an
  /// ArgumentError will be thrown
  ///
  /// The 'color` may be null or un-passed, in that case, a default value will
  /// be assigned to it
  TextStyle textStyle({
    required TextStyle textStyle,
    Color? color,
  }) {
    ArgumentError.checkNotNull(textStyle, 'textStyle');

    color ??= DarkThemeColors.base01;

    return getStyle(textStyle: textStyle, color: color);
  }

  void updateTheme({required Brightness brightness}) =>
      _isDarkTheme = brightness == Brightness.dark;
}
