name: deriv_feature_flag
description: wrapper to handle feature flag for deriv applications
version: 0.1.2+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  growthbook_sdk_flutter: ^3.0.0+0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
